### ISSUE TITLE
Truncated deployment ID

### ISSUE THREAD

**Issue by kevinsbarnard** [mbari-media-management/panoptes#3]
I'm noticing that Panoptes will give a URI with a truncated deployment ID; for example, "0025" becomes "25". Maybe there's a step where the deployment ID is converted to a number and back to a string?

Example: 
`GET http://m3.shore.mbari.org/panoptes/v1/images/Doc%20Ricketts/0782/06_24_07_09.png`
gives
```
{
    "cameraId": "Doc Ricketts",
    "deploymentId": "0782",
    "name": "06_24_07_09.png",
    "uri": "http://search.mbari.org/ARCHIVE/framegrabs/Doc%20Ricketts/images/782/06_24_07_09.png"
}
```
where the true URI for the image is `http://search.mbari.org/ARCHIVE/framegrabs/Doc%20Ricketts/images/0782/06_24_07_09.png`.

Not a big issue, but I just want to ensure I'm uploading the processed images to the same spot as the original ones and linking the correct returned URL in VARS.

**Comment by hohonuuli** [comment]
Fixed: `GET http://m3.shore.mbari.org/panoptes/v1/images/Doc%20Ricketts/0782/06_24_07_09.png`

```json
{
  "uri":"http://search.mbari.org/ARCHIVE/framegrabs/Doc%20Ricketts/images/0782/06_24_07_09.png",
  "cameraId":"Doc Ricketts",
  "deploymentId":"0782",
  "name":"06_24_07_09.png"
}
```

**Comment by hohonuuli** [comment]
This change has been deployed internally at MBARI
